### ISSUE TITLE
Migrating this repo to the 'ucsf-wynton' GitHub org (from 'UCSF-HPC')

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#46]
FYI, I'll be moving this repo from https://github.com/UCSF-HPC/wynton/ to https://github.com/ucsf-wynton/wynton/ for the purpose of tidying up.  I think I can do that while keeping <https://wynton.ucsf.edu/hpc/> up and running.

# Tasks

* [x] Transfer repo from UCSF-HPC to ucsf-wynton
* [x] Update wynton-web server to pull from the new repo
* [x] README: Update to point to the new GitHub Pages mirror URL
* [x] README: Update to new git clone URL
* [x] Rename repo from too-generic 'wynton' to 'wynton-website-hpc'
* [x] Wait for 24 hours to confirm everything works smoothly
